# Generated by Django 3.0.3 on 2020-09-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciver_user', models.CharField(choices=[('is_user', 'user'), ('is_operator', 'operator')], default='is_admin', max_length=20)),
                ('title', models.CharField(max_length=60)),
                ('date_message', models.DateTimeField(auto_now_add=True)),
                ('send_content', models.TextField()),
                ('visualized', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('messageType', models.CharField(default='send', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseMeesage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
