# Generated by Django 3.0.3 on 2020-05-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200513_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_replay',
            field=models.BooleanField(default=False),
        ),
    ]
