# Generated by Django 3.0.3 on 2020-05-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_is_replay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_replay',
        ),
    ]
