# Generated by Django 3.0.3 on 2020-09-28 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200928_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=1, max_length=11, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
