CREATE OR REPLACE FUNCTION TG_CREATE_NEW_STATION_TABLE()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS
	$$
		DECLARE
			NEW_STATION_NAME VARCHAR(20) := 'STATION';
		BEGIN
			NEW_STATION_NAME := CONCAT(NEW_STATION_NAME, TO_CHAR(NEW.ID, 'FM999999999999999999'));

			UPDATE stations_setup
			SET TABLE_NAME = NEW_STATION_NAME
			WHERE ID = NEW.ID;
			
			EXECUTE FORMAT
			('
			CREATE TABLE %s
			(
			WEEK INTEGER NOT NULL,
			T DOUBLE PRECISION NOT NULL,
			A_X DOUBLE PRECISION NOT NULL,
			A_Y DOUBLE PRECISION NOT NULL,
			A_Z DOUBLE PRECISION NOT NULL,
			TEMP DOUBLE PRECISION,
			PRIMARY KEY(WEEK, T)
			);
			
			CREATE INDEX INDEX_%s ON %s(WEEK, T);

			', NEW_STATION_NAME
		, NEW_STATION_NAME
		, NEW_STATION_NAME);
			
		RETURN NULL;
		END;
	$$;

CREATE TRIGGER CREATE_NEW_STATION_TABLE
AFTER INSERT
	ON stations_setup
FOR EACH ROW
EXECUTE PROCEDURE TG_CREATE_NEW_STATION_TABLE();
