# Generated by Django 3.0.3 on 2020-04-30 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to=stations.models.station_directory_path)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Setup')),
            ],
        ),
    ]
