# Generated by Django 3.0.3 on 2020-04-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='data',
            new_name='date',
        ),
        migrations.CreateModel(
            name='Deactivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('operator_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.Setup')),
            ],
        ),
    ]
