# Generated by Django 3.0.3 on 2020-04-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_auto_20200430_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='operator_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
