# Generated by Django 3.0.3 on 2020-04-30 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stations', '0004_auto_20200430_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivate',
            name='operator_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deactivate',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivate', to='stations.Setup'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='setup',
            name='operator_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='setup',
            name='station_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
