# Generated by Django 3.0.3 on 2020-04-30 12:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0005_auto_20200430_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='id',
            field=models.UUIDField(default=uuid.UUID('929148f2-44a1-4e57-92b2-2cbc1df51557'), editable=False, primary_key=True, serialize=False),
        ),
    ]
