# Generated by Django 3.0.3 on 2020-04-30 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_auto_20200430_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivate',
            name='station_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deactivates', to='stations.Setup'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
