# Generated by Django 3.0.3 on 2020-05-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_auto_20200430_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivate',
            name='operator_name',
            field=models.CharField(max_length=150),
        ),
    ]
